# Different themes have different required and optional fields, look at the documentation for your intended theme to see which you need and/or are available
name: Devon Anirudh
background: https://images.unsplash.com/photo-1544198365-f5d60b6d8190?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80 # An image to use as a background for the site
avatar: https://startbootstrap.github.io/startbootstrap-freelancer/assets/img/avataaars.svg # The avatar/profile picture of the person's site (put image in images folder and then just the image name here)
email: devon@devonanirudh.com
phone: 123-123-123454
biography: | # The '|' Used to allow the description to go across multiple lines
  I am a technologist that Blends academic training in business management and data analytics with hands-on experience in systems administration and training to offer employers a track record of delivering on tasks accurately, efficiently and quickly.
  Known for best-in-class attention to detail and  communications with stakeholders across all levels.
role: Lead Technical Specialist
company: Columbia University Center for Teaching and Learning
social:
  github: devonanirudh # Your username on github 
  linkedin: danirudh # go to linkedin and go to your profile, your name will be at the end of the url i.e. www.linkedin.com/in/<name>
  url: https://cv.devonanirudh.com # The URL the site will be hosted on (used by resume)
examples: false # If you want to include the example.md files in your final build (good for developing new themes)
theme: dimension # The theme you want to use for your site
ua_code: UA-000000-0 # The UA code for google analytics
resume: true # Whether to generate the resume page or not
ignore_exif_data : false # Whether to ignore exif data for gallery images